#!/bin/bash

#change path as desired
pdf_file_path="/Users/sulemanbasit/PycharmProjects/Calgary-Transit-Economic-Gap-Analysis/Data Sets/Community Profiles"

cd "$pdf_file_path"

# headers
echo "Community Name,Population in private households,0 to 14 years,65 to 84 years,85 years and over,Population aged 15 years and over in private households,In the labor force,Employed,Self-Employed,Unemployed,Median income of population aged 15 years and over,Median household income of private households,Private households,Under $20000,$20000 to $39999,Population in private households to whom low income concepts are applicable (Number),Population in private households to whom low income concepts are applicable (Number in low income),0 to 17 years (Number),0 to 17 years (Number in low income),18 to 64 years (Number),18 to 64 years (Number in low income),65 years and over (Number),65 years and over (Number in low income),Private households with income,Households spending less than 30% of total income on shelter,Private households with total income greater than zero (Owner),Private households with total income greater than zero (Renter),Per cent households with income spending 30% or more total income on shelter (Owner),Per cent households with income spending 30% or more total income on shelter (Renter),Employed labour force aged 15 years and over in private households,Driver – car truck or van,Passenger – car truck or van,Public transit,Walked,Bicycle,Other methods,Employed labour force aged 15 years and over in private households2,Less than 15 minutes,15 to 29 minutes,30 to 44 minutes,45 to 59 minutes,Employed labour force aged 15 years and over in private households3,Between 5 a.m. and 5:59 a.m.,Between 6 a.m. and 6:59 a.m.,Between 7 a.m. and 7:59 a.m.,Between 8 a.m. and 8:59 a.m.,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m." > ~/Desktop/demand.csv

# pdftotext -layout "falconridge.pdf" ~/Desktop/community_txt.txt

for file in *; do
	if [ "$file" = "pine-creek.pdf" ]; then
        	continue  # Skip this iteration
	fi
	pdftotext -layout "$file" ~/Desktop/community_txt.txt
	# echo -n "$file," >> ~/Desktop/demand.csv
	head -n 3 ~/Desktop/community_txt.txt | tail -n 1 | awk -F '[ ]{2,}' '{print $2}' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt| grep '0 to 14' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' 'NR==8 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat -n ~/Desktop/community_txt.txt| grep '0 to 14 years' | awk -F '[ ]{2,}' '{print $3}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat -n ~/Desktop/community_txt.txt| grep '65 to 84 years' | awk -F '[ ]{2,}' '{print $3}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat -n ~/Desktop/community_txt.txt| grep '85 years and over' | awk -F '[ ]{2,}' '{print $3}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv

	cat ~/Desktop/community_txt.txt| grep 'years and over in' | awk -F '[ ]{2,}' 'NR==1 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat  ~/Desktop/community_txt.txt| grep 'In the labour force' | awk -F '[ ]{2,}' 'NR==1 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat ~/Desktop/community_txt.txt| grep -w Employed | awk -F '[ ]{2,}' 'NR==1 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat ~/Desktop/community_txt.txt| grep -w Employed | awk -F '[ ]{2,}' 'NR==2 {print $3}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	cat ~/Desktop/community_txt.txt| grep Unemployed | awk -F '[ ]{2,}' 'NR==1 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv

	if [ "$file" = "bowness.pdf" ]; then
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==8 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==13 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==8 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==7 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==8 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	elif [ "$file" = "bayview.pdf" ] || [ "$file" = "bel-aire.pdf" ]; then
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==6 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==13 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==6 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==7 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==8 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	else
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==6 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' 'NR==11 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==4 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==5 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
		head -n $(($(cat -n ~/Desktop/community_txt.txt | grep Income | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}')+25)) ~/Desktop/community_txt.txt | tail -n 25  | awk -F '[ ]{2,}' '{print $0}' | tail | awk -F '[ ]{2,}' 'NR==6 {print $2}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	fi

	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}'| awk -F '[ ]{1,}' 'NR==1 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}'| awk -F '[ ]{1,}' 'NR==1 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}'| awk -F '[ ]{1,}' 'NR==3 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}'| awk -F '[ ]{1,}' 'NR==3 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}'| awk -F '[ ]{1,}' 'NR==4 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}'| awk -F '[ ]{1,}' 'NR==4 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}'| awk -F '[ ]{1,}' 'NR==5 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Population in private households to whom low' | awk -F '[ ]{1,}' '{print $2}' | awk 'NR==2 {print $1}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}'| awk -F '[ ]{1,}' 'NR==5 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '30% or more of total' | awk -F '[ ]{1,}' '{print $2}' | awk -F '[ ]{2,}' '{print}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}' | awk -F '[ ]{2,}' 'NR==4 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '30% or more of total' | awk -F '[ ]{1,}' '{print $2}' | awk -F '[ ]{2,}' '{print}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}' | awk -F '[ ]{2,}' 'NR==10 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt| grep 'greater than zero' | awk -F '[ ]{2,}' '{print}' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==9 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt| grep 'greater than zero' | awk -F '[ ]{2,}' '{print}' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}' | awk -F '[ ]{1,}' 'NR==9 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt| grep 'income on shelter' | awk -F '[ ]{2,}' '{print}' | awk -F '[ ]{1,}' 'NR==4 {print $2}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==8 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt| grep 'income on shelter' | awk -F '[ ]{2,}' '{print}' | awk -F '[ ]{1,}' 'NR==4 {print $2}') ~/Desktop/community_txt.txt | tail | awk -F '[ ]{2,}' '{print $3}' | awk -F '[ ]{1,}' 'NR==8 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv

	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==1 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==3 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==5 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==7 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==8 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==9 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==10 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv

	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==1 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '60 minutes and over' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==6 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '60 minutes and over' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==7 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '60 minutes and over' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==8 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '60 minutes and over' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==9 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv

	head -n $(cat -n ~/Desktop/community_txt.txt | grep 'Other methods' | awk -F '[ ]{1,}' '{print $2}') ~/Desktop/community_txt.txt | tail | awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' 'NR==1 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==9 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==12 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==15 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==18 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==21 {print}' | sed 's/,//g' | awk '{printf "%s,", $0}' >> ~/Desktop/demand.csv
	head -n $(cat -n ~/Desktop/community_txt.txt | grep '4:59 a.m.' | awk -F '[ ]{1,}' 'NR==1 {print $2}') ~/Desktop/community_txt.txt | tail -n 25| awk -F'[ ]{2,}' '{print $2}' | awk -F '[ ]{1,}' ' NR==24 {print}' | sed 's/,//g' >> ~/Desktop/demand.csv

done
